# Generated by Django 4.1.2 on 2022-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdminCaptcha',
            fields=[
                ('key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=512, null=True)),
                ('subject', models.CharField(max_length=9, null=True)),
                ('response', models.CharField(max_length=9, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyAntiSpam',
            fields=[
                ('key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=512, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyIpBanList',
            fields=[
                ('ip', models.GenericIPAddressField(default=None, primary_key=True, serialize=False)),
                ('key', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=255)),
                ('action', models.CharField(max_length=512, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyVerifCode',
            fields=[
                ('key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=512, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyVisitor',
            fields=[
                ('key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('os', models.CharField(max_length=512, null=True)),
                ('browser', models.CharField(max_length=512, null=True)),
                ('device', models.CharField(max_length=512, null=True)),
                ('language', models.CharField(max_length=512, null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('processor', models.IntegerField(null=True)),
                ('pdf', models.BooleanField(null=True)),
                ('webdriver', models.BooleanField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('country', models.CharField(max_length=512, null=True)),
                ('city', models.CharField(max_length=512, null=True)),
                ('agent', models.CharField(max_length=512, null=True)),
                ('referer', models.URLField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
