# Generated by Django 5.0 on 2023-12-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAdminCaptcha',
        ),
        migrations.DeleteModel(
            name='MyAntiSpam',
        ),
        migrations.DeleteModel(
            name='MyIpBanList',
        ),
        migrations.DeleteModel(
            name='MyUserLog',
        ),
        migrations.DeleteModel(
            name='MyVerifCode',
        ),
        migrations.DeleteModel(
            name='MyVisitor',
        ),
    ]
